apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v4te20wem-go 
  janus-idp.io/tekton: v4te20wem-go
  backstage.io/kubernetes-id: v4te20wem-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v4te20wem-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml